apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8snorootcontainers
metadata:
  name: k8snorootcontainers
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment","ReplicaSet", "StatefulSet", "DaemonSet"]
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    message: "Containers running as root are not allowed."
