apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8srequirednamespace
metadata:
  name: ns-must-be-intern
  namespace: intern
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["*"]
    excludedNamespaces:
    - default
    - cert-manager
    - ingress-nginx
    - keycloak
    - kube-*
    - observability
  parameters:
    labels: intern = "true"