apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
  namespace: intern
spec:
  containers:
  - name: myapp
    image: jirivasm/hello-wolrd-pyton:latest
    #securityContext: 
      #runAsNonRoot: false
    resources:
      limits:
        memory: "2Gi"
        cpu: "500m"
    ports:
      - containerPort: 5000
