apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
  namespace: myapp
  labels:
    app: flask-demo
    type: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo
      type: demo
  template:
    metadata:
      labels:
        app: flask-demo
        type: demo
    spec:
      containers:
      - name: flask-demo
        image: jirivasm/hello-wolrd-pyton:latest
        securityContext:
          #privileged: true
          #privileged is not allowed
          runAsNonRoot: false
          capabilities:
            drop: ["ALL"]
          
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      
       