apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8snorootcontainers
spec:
  crd:
    spec:
      names:
        kind: k8snorootcontainers
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snorootcontainers
        violation[{"msg": msg, "details": {}}] {
          c := input_containers[_]
          not c.securityContext.runAsNonRoot
          msg := sprintf("Containers running as root or without runAsNonRoot are not allowed: %v, securityContext: %v", [c.name, c.securityContext])
        }
        input_containers[c] { c := input.review.object.spec.containers[_] }
        input_containers[c] { c := input.review.object.spec.initContainers[_]
