apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-policy-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-policy-agent.github.io/kube-mgmt/charts
    targetRevision: 8.5.7
    chart: opa-kube-mgmt
  destination:
    server: https://kubernetes.default.svc
    namespace: opa
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
